<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Matrices" data-toc-modified-id="Matrices-1">Matrices</a></span><ul class="toc-item"><li><span><a href="#Extraction-d'un-élément-d'une-matrice" data-toc-modified-id="Extraction-d'un-élément-d'une-matrice-1.1">Extraction d'un élément d'une matrice</a></span></li><li><span><a href="#diag" data-toc-modified-id="diag-1.2">diag</a></span></li><li><span><a href="#Opértaion-sur-les-matrices" data-toc-modified-id="Opértaion-sur-les-matrices-1.3">Opértaion sur les matrices</a></span></li><li><span><a href="#cbind" data-toc-modified-id="cbind-1.4">cbind</a></span></li><li><span><a href="#rbind" data-toc-modified-id="rbind-1.5">rbind</a></span></li><li><span><a href="#matrcice-en-vecteur" data-toc-modified-id="matrcice-en-vecteur-1.6">matrcice en vecteur</a></span></li><li><span><a href="#Quelques-fonctions-statistiques-sur-les-matrices" data-toc-modified-id="Quelques-fonctions-statistiques-sur-les-matrices-1.7">Quelques fonctions statistiques sur les matrices</a></span></li><li><span><a href="#Corrélation" data-toc-modified-id="Corrélation-1.8">Corrélation</a></span></li><li><span><a href="#summary" data-toc-modified-id="summary-1.9">summary</a></span></li></ul></li><li><span><a href="#Générer-des-variables-aléatoires" data-toc-modified-id="Générer-des-variables-aléatoires-2">Générer des variables aléatoires</a></span><ul class="toc-item"><li><span><a href="#runif" data-toc-modified-id="runif-2.1">runif</a></span></li><li><span><a href="#Seed" data-toc-modified-id="Seed-2.2">Seed</a></span></li><li><span><a href="#Sample-(échantillonage)" data-toc-modified-id="Sample-(échantillonage)-2.3">Sample (échantillonage)</a></span></li><li><span><a href="#rnorm" data-toc-modified-id="rnorm-2.4">rnorm</a></span></li></ul></li></ul></div>

# Matrices

Une matrice est un objet constitué de données en deux dimensions, soit des lignes et des colonnes. Chaque élément de la matrice est situé à l'intersection d'une ligne et d'une colonne.

In [56]:
A<- matrix(c(6,8,1,1,4,2), nrow = 2, ncol = 3)

In [57]:
A

[,1] [,2] [,3]
[1,] 6    1    4   
[2,] 8    1    2

Il arrive souvent qu'on veuille transposer une matrice. Pour ce faire, il suffit de l'inclure à l'intérieur de `t(matrice)`

In [58]:
t(A)

[,1] [,2]
[1,] 6    8   
[2,] 1    1   
[3,] 4    2

**Note** Lorsqu'on transpose un vecteur, R transforme ce vecteur en une matrice à une seule dimension:

In [59]:
vec<-1:5

In [61]:
t(vec)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5

**Note** la fonction `dim()` donne les dimensions d'une matrice. Si l’on vérifie la dimension du vecteur.

In [62]:
dim(vec)

NULL

Bien évidemment il nous retourne une valeur nulle. Mais lorsqu'on transforme ce vecteur en matrice, on obtient;

In [63]:
dim(t(vec))

[1] 1 5

Ce qui veut dire que notre matrice est composée d'une seule ligne et cinq colonnes

## Extraction d'un élément d'une matrice

Si l'on veut extraire un élément d'une matrice, il suffit d'indiquer ses coordonnées **`[ligne, colonne]`**

In [64]:
A[1,3]

[1] 4

In [65]:
A

[,1] [,2] [,3]
[1,] 6    1    4   
[2,] 8    1    2

Lorsqu'on veut extraire un élément qui n'existe pas dans la matrice, on obtien alors le message d'erreur `subscript out of bounds`. Un message d'erreur que nous verrons souvent!

In [67]:
A[1,4]

ERROR: Error in A[1, 4]: subscript out of bounds


Si l'on omet de mettre une valeur au numéro de colonne ou de ligne, on obtient la ligne ou la colonne complète

In [68]:
A[,1]

[1] 6 8

Lorsqu'on crée une matrice, nous ne sommes pas obligés d'indiquer le nombre de colonnes ou de lignes en même temps. Un seul argument suffit.

In [81]:
B<-matrix(seq(1,9.5,.5), 3)

In [82]:
B

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1.0  2.5  4.0  5.5  7.0  8.5 
[2,] 1.5  3.0  4.5  6.0  7.5  9.0 
[3,] 2.0  3.5  5.0  6.5  8.0  9.5

Si l'on veut extraire la deuxième et la quatrième colonne

In [83]:
B[,c(2,4)]

[,1] [,2]
[1,] 2.5  5.5 
[2,] 3.0  6.0 
[3,] 3.5  6.5

In [78]:
B<-t(B)

In [79]:
B

[,1] [,2] [,3]
[1,] 1.0  1.5  2.0 
[2,] 2.5  3.0  3.5 
[3,] 4.0  4.5  5.0 
[4,] 5.5  6.0  6.5 
[5,] 7.0  7.5  8.0 
[6,] 8.5  9.0  9.5

Si l'on veut extraire la troisième et la cinquième ligne;

In [80]:
B[c(3,5),]

[,1] [,2] [,3]
[1,] 4    4.5  5   
[2,] 7    7.5  8

## diag

Cette fonction crée une matrice identité, c'est une matrice carrée avec des 1 sur la diagonale et des 0 partout ailleurs.

In [84]:
diag(5)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    1    0    0    0   
[3,] 0    0    1    0    0   
[4,] 0    0    0    1    0   
[5,] 0    0    0    0    1

## Opértaion sur les matrices

On peut aussi appliquer des fonctions mathématiques sur des matrices comme nous l'avons fait avec des vecteurs

In [85]:
A**2

[,1] [,2] [,3]
[1,] 36   1    16  
[2,] 64   1     4

In [86]:
B/2

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0.50 1.25 2.00 2.75 3.50 4.25
[2,] 0.75 1.50 2.25 3.00 3.75 4.50
[3,] 1.00 1.75 2.50 3.25 4.00 4.75

In [89]:
C<-B*2

In [90]:
B+C

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 3.0   7.5 12.0 16.5 21.0 25.5
[2,] 4.5   9.0 13.5 18.0 22.5 27.0
[3,] 6.0  10.5 15.0 19.5 24.0 28.5

Créons une matrice `A=5X3`. Cette matrice contient les températures en Fahrenheit des trois villes "Fairbanks","San Francisco" et "Chicago" (nom de colonnes). Les lignes sont les données du mois de mars 2012 au mois de mars 2016.

In [6]:
A<-matrix(c(30,32,31,27,36,72,60,78,67,71,55,57,56,55,49),ncol=3)
A

[,1] [,2] [,3]
[1,] 30   72   55  
[2,] 32   60   57  
[3,] 31   78   56  
[4,] 27   67   55  
[5,] 36   71   49

Convertissons ces données en Celsius avec la formule suivante;

\begin{equation}\label{eq:}
℃= \frac{℉-32}{1.8000}
\end{equation}


In [7]:
A<-round((A-32)/1.8,0)
A

[,1] [,2] [,3]
[1,] -1   22   13  
[2,]  0   16   14  
[3,] -1   26   13  
[4,] -3   19   13  
[5,]  2   22    9

On peut donner des noms à chacune des colonnes avec la fonction `colnames()`

In [8]:
colnames(A)<-c("Fairbanks","San Francisco","Chicago")

et des nom aux lignes avec la fonction `rownames()`

In [9]:
rownames(A)<-paste("3/",12:16,sep='')

La fonction `paste` ci-haut permet de concatener des caractères 

In [10]:
paste("3/",12:16,sep='___')

[1] "3/___12" "3/___13" "3/___14" "3/___15" "3/___16"

In [11]:
A

Fairbanks San Francisco Chicago
3/12 -1        22            13     
3/13  0        16            14     
3/14 -1        26            13     
3/15 -3        19            13     
3/16  2        22             9

Créons une autre matrice `B`

In [12]:
B<-matrix(c(88,85,83,81,78,62,61,54,60,65,90,92,91,89,90),ncol=3)
colnames(B)<-c("Los Angeles","Seattle","Honolulu")
rownames(B)<-paste("3/",12:16,sep='')

In [13]:
B<-round((B-32)/1.8,0)
B

Los Angeles Seattle Honolulu
3/12 31          17      32      
3/13 29          16      33      
3/14 28          12      33      
3/15 27          16      32      
3/16 26          18      32

## cbind

La fonction `cbind` permet de concaténer deux matrices ensemble en colonne

In [14]:
cbind(A,B)

Fairbanks San Francisco Chicago Los Angeles Seattle Honolulu
3/12 -1        22            13      31          17      32      
3/13  0        16            14      29          16      33      
3/14 -1        26            13      28          12      33      
3/15 -3        19            13      27          16      32      
3/16  2        22             9      26          18      32

## rbind

La fonction `rbind` permet de concaténer deux matrices ensemble une par-dessus l'autre

In [15]:
rbind(A,B)

Fairbanks San Francisco Chicago
3/12 -1        22            13     
3/13  0        16            14     
3/14 -1        26            13     
3/15 -3        19            13     
3/16  2        22             9     
3/12 31        17            32     
3/13 29        16            33     
3/14 28        12            33     
3/15 27        16            32     
3/16 26        18            32

## matrcice en vecteur

On peut aussi transformer une matrice en un vecteur;

Reprenons la matrice que nous avons créée avec la fonction `rbind`. On lui donne le nom "mat_comb"

In [16]:
mat_comb<-cbind(A,B)

On la transforme en vecteur avec `c(nomMatrice)`

In [17]:
c(mat_comb)

[1] -1  0 -1 -3  2 22 16 26 19 22 13 14 13 13  9 31 29 28 27 26 17 16 12 16 18
[26] 32 33 33 32 32

## Quelques fonctions statistiques sur les matrices

In [18]:
mat_comb

Fairbanks San Francisco Chicago Los Angeles Seattle Honolulu
3/12 -1        22            13      31          17      32      
3/13  0        16            14      29          16      33      
3/14 -1        26            13      28          12      33      
3/15 -3        19            13      27          16      32      
3/16  2        22             9      26          18      32

Lorsqu'on applique la fonction `min`, on obtient alors la valeur minimale de toutes les valeurs contenues dans la matrice

In [19]:
min(mat_comb)

[1] -3

In [20]:
max(mat_comb)

[1] 33

In [21]:
range(mat_comb)

[1] -3 33

In [22]:
sd(mat_comb)

[1] 11.19236

Les statistiques que nous venons d'obtenir, sont applquées à toutes les valeurs de la matrice. Et si nous voulions des statistiques par ligne ou par colonne

In [23]:
rowMeans(mat_comb)

3/12     3/13     3/14     3/15     3/16 
19.00000 18.00000 18.50000 17.33333 18.16667

In [24]:
colMeans(mat_comb)

Fairbanks San Francisco       Chicago   Los Angeles       Seattle 
         -0.6          21.0          12.4          28.2          15.8 
     Honolulu 
         32.4

## Corrélation

In [33]:
cor(mat_comb)

Fairbanks   San Francisco Chicago    Los Angeles Seattle    
Fairbanks      1.00000000  0.07356124   -0.6918586 -0.24325462  0.38624364
San Francisco  0.07356124  1.00000000   -0.3084798 -0.06947125 -0.49810768
Chicago       -0.69185856 -0.30847978    1.0000000  0.64005690 -0.48366537
Los Angeles   -0.24325462 -0.06947125    0.6400569  1.00000000 -0.04559608
Seattle        0.38624364 -0.49810768   -0.4836654 -0.04559608  1.00000000
Honolulu       0.05025189  0.00000000    0.5151222  0.14237370 -0.72057669
              Honolulu   
Fairbanks      0.05025189
San Francisco  0.00000000
Chicago        0.51512220
Los Angeles    0.14237370
Seattle       -0.72057669
Honolulu       1.00000000

## summary

In [34]:
summary(mat_comb)

   Fairbanks    San Francisco    Chicago      Los Angeles      Seattle    
 Min.   :-3.0   Min.   :16    Min.   : 9.0   Min.   :26.0   Min.   :12.0  
 1st Qu.:-1.0   1st Qu.:19    1st Qu.:13.0   1st Qu.:27.0   1st Qu.:16.0  
 Median :-1.0   Median :22    Median :13.0   Median :28.0   Median :16.0  
 Mean   :-0.6   Mean   :21    Mean   :12.4   Mean   :28.2   Mean   :15.8  
 3rd Qu.: 0.0   3rd Qu.:22    3rd Qu.:13.0   3rd Qu.:29.0   3rd Qu.:17.0  
 Max.   : 2.0   Max.   :26    Max.   :14.0   Max.   :31.0   Max.   :18.0  
    Honolulu   
 Min.   :32.0  
 1st Qu.:32.0  
 Median :32.0  
 Mean   :32.4  
 3rd Qu.:33.0  
 Max.   :33.0  

 Si on veut par ligne, rappelons-nous que nous avons appris à transposer les matrices!

In [35]:
summary(t(mat_comb))

      3/12            3/13            3/14            3/15      
 Min.   :-1.00   Min.   : 0.00   Min.   :-1.00   Min.   :-3.00  
 1st Qu.:14.00   1st Qu.:14.50   1st Qu.:12.25   1st Qu.:13.75  
 Median :19.50   Median :16.00   Median :19.50   Median :17.50  
 Mean   :19.00   Mean   :18.00   Mean   :18.50   Mean   :17.33  
 3rd Qu.:28.75   3rd Qu.:25.75   3rd Qu.:27.50   3rd Qu.:25.00  
 Max.   :32.00   Max.   :33.00   Max.   :33.00   Max.   :32.00  
      3/16      
 Min.   : 2.00  
 1st Qu.:11.25  
 Median :20.00  
 Mean   :18.17  
 3rd Qu.:25.00  
 Max.   :32.00  

# Générer des variables aléatoires

## runif
La fonction `runif` permet de générer des pseudo-variables aléatoires indépendantes entre deux bornes
`runif(n=combien, min, max)`

In [40]:
runif(1,0,10)

[1] 3.350236

In [41]:
runif(10,0,1)

[1] 0.76283694 0.60481794 0.06360721 0.05281462 0.42951670 0.32701553
 [7] 0.42539012 0.09306086 0.20397331 0.04200240

On peut insérer maintenant les valeurs générées à l'intérieur d'un vecteur

In [44]:
x<-runif(100,0,1)
x

[1] 0.539611001 0.969200172 0.161860105 0.446521448 0.007107472 0.963198963
  [7] 0.579066600 0.165705290 0.594905792 0.375249445 0.437035386 0.988691223
 [13] 0.446837737 0.547483164 0.024456179 0.402985492 0.349131921 0.740115433
 [19] 0.277191532 0.843555369 0.857099119 0.458788801 0.053068328 0.927752252
 [25] 0.353458901 0.568380536 0.230667704 0.337636061 0.375225967 0.387821003
 [31] 0.459963123 0.272586000 0.377333411 0.998247936 0.445947563 0.815888306
 [37] 0.205926697 0.145684424 0.829736990 0.863744982 0.974668300 0.588302414
 [43] 0.755799307 0.549724115 0.779031443 0.031087626 0.412300328 0.566727907
 [49] 0.498380967 0.709585281 0.915065909 0.780876428 0.178426814 0.639498161
 [55] 0.439221660 0.797969023 0.708209967 0.219743495 0.388405615 0.334317806
 [61] 0.125142667 0.205675625 0.305508881 0.686442974 0.864465568 0.608728708
 [67] 0.288030886 0.158349109 0.323984491 0.389953878 0.180025292 0.644314111
 [73] 0.414720709 0.986791231 0.340648489 0.574771377 0.933746692 0.227020583
 [79] 0.105411230 0.695686528 0.632969576 0.820697319 0.438879429 0.030912827
 [85] 0.560534958 0.079159309 0.775976541 0.061341432 0.803953293 0.908220875
 [91] 0.127778964 0.199427006 0.604085021 0.580892457 0.463377882 0.437255925
 [97] 0.885360277 0.293950659 0.168015816 0.805729570

Ou les insérer à l'intérieur d'une matrice

In [45]:
x<-matrix(x, 10)
x

[,1]        [,2]       [,3]       [,4]      [,5]       [,6]     
 [1,] 0.539611001 0.43703539 0.85709912 0.4599631 0.97466830 0.9150659
 [2,] 0.969200172 0.98869122 0.45878880 0.2725860 0.58830241 0.7808764
 [3,] 0.161860105 0.44683774 0.05306833 0.3773334 0.75579931 0.1784268
 [4,] 0.446521448 0.54748316 0.92775225 0.9982479 0.54972412 0.6394982
 [5,] 0.007107472 0.02445618 0.35345890 0.4459476 0.77903144 0.4392217
 [6,] 0.963198963 0.40298549 0.56838054 0.8158883 0.03108763 0.7979690
 [7,] 0.579066600 0.34913192 0.23066770 0.2059267 0.41230033 0.7082100
 [8,] 0.165705290 0.74011543 0.33763606 0.1456844 0.56672791 0.2197435
 [9,] 0.594905792 0.27719153 0.37522597 0.8297370 0.49838097 0.3884056
[10,] 0.375249445 0.84355537 0.38782100 0.8637450 0.70958528 0.3343178
      [,7]      [,8]      [,9]       [,10]    
 [1,] 0.1251427 0.1800253 0.63296958 0.1277790
 [2,] 0.2056756 0.6443141 0.82069732 0.1994270
 [3,] 0.3055089 0.4147207 0.43887943 0.6040850
 [4,] 0.6864430 0.9867912 0.03091283 0.5808925
 [5,] 0.8644656 0.3406485 0.56053496 0.4633779
 [6,] 0.6087287 0.5747714 0.07915931 0.4372559
 [7,] 0.2880309 0.9337467 0.77597654 0.8853603
 [8,] 0.1583491 0.2270206 0.06134143 0.2939507
 [9,] 0.3239845 0.1054112 0.80395329 0.1680158
[10,] 0.3899539 0.6956865 0.90822088 0.8057296

Nous avons maintenant obtenu une matrice de dimension 10X10

## Seed

Comme dans SAS, nous avons appris comment générer les mêmes variables aléatoires dans un contexte de cumulation par exemple, avec la fonction seed

In [151]:
set.seed(2)

In [152]:
runif(2,0,1) 

[1] 0.1848823 0.7023740

In [153]:
runif(2,0,1) 

[1] 0.5733263 0.1680519

In [154]:
runif(2,0,1) 

[1] 0.9438393 0.9434750

Si on remet le seed=2, on obtient alors les mêmes valeurs que nous avons obtenues auparavant

In [159]:
set.seed(2)

In [160]:
runif(2,0,1) 

[1] 0.1848823 0.7023740

In [161]:
runif(2,0,1) 

[1] 0.5733263 0.1680519

In [162]:
runif(2,0,1) 

[1] 0.9438393 0.9434750

## Sample (échantillonage)

La fonction `sample` tire un échantillon aléatoire de $n$ variables à partir d'un ensemble de données allant de $\left\{1, \dots ,N\right\}$

In [168]:
sample(1:10,5)

[1] 2 8 7 4 9

In [169]:
sample(x,5)

[1] 0.4676159 0.5859861 0.3184056 0.1172594 0.8089555

In [170]:
sample(x,5)

[1] 0.08456684 0.69311989 0.84903890 0.41026086 0.88457494

$n\leq N$

In [172]:
sample(x,length(x)+1)

ERROR: Error in sample.int(length(x), size, replace, prob): cannot take a sample larger than the population when 'replace = FALSE'


Lorsque notre échantillon tiré est plus grand que notre ensemble de données, on peut utiliser un tirage avec remise:

In [175]:
sample(0:1, 100, replace = T)

[1] 1 0 0 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 1 1 1
 [38] 1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0
 [75] 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 1 1

Cette fonction fonctionne aussi sur un tirage de variable de type caractères

In [176]:
sample(state.name, 5)

[1] "Kentucky"       "Montana"        "Delaware"       "Wyoming"       
[5] "North Carolina"

La fonction `sample` donne des probabilités égales à tous les éléments tirés d'un ensemble de données. Toutesfois, il est possible de préciser la probabilité de chaque élément tiré.

In [1]:
s<-sample(1:5, 1000, replace=T, prob=c(.2,.2,.2,.2,.2))
s

[1] 5 4 4 5 1 1 1 1 5 1 1 1 1 3 5 2 5 4 1 3 3 5 4 2 3 4 4 5 2 4 5 2 4 3 1 5 5
  [38] 3 5 5 3 5 1 5 1 4 1 5 5 2 4 4 5 2 5 5 4 3 4 5 2 1 3 1 3 2 3 4 5 2 5 4 4 4
  [75] 4 2 5 3 2 2 1 2 4 1 4 2 1 1 4 2 1 3 5 1 4 4 5 2 2 1 1 4 1 5 4 2 5 2 5 1 4
 [112] 4 1 2 3 4 4 5 2 3 5 3 5 3 3 3 5 2 2 5 1 2 5 2 4 3 2 3 4 5 3 1 2 2 3 1 3 1
 [149] 5 4 4 1 2 4 4 2 1 3 1 4 1 2 5 4 3 3 1 4 2 5 3 1 5 1 5 4 5 5 4 1 1 2 2 1 3
 [186] 3 3 1 3 5 2 2 4 3 4 5 4 3 5 5 3 2 5 5 2 2 2 1 2 2 4 3 2 2 4 1 1 1 3 1 4 3
 [223] 4 1 3 1 2 3 4 4 4 5 2 1 1 5 1 3 5 4 4 3 4 3 2 5 2 2 2 3 4 1 1 1 3 4 3 1 3
 [260] 1 1 3 1 5 3 1 2 5 5 3 5 3 5 5 3 3 5 5 1 2 4 1 2 4 1 4 3 2 3 1 2 3 1 3 3 3
 [297] 1 3 5 3 5 2 2 5 5 5 1 1 4 1 2 3 5 4 4 5 4 2 2 2 1 1 2 2 3 1 2 5 3 3 4 4 5
 [334] 3 5 3 3 3 2 2 2 2 4 3 1 4 2 3 2 3 5 5 5 3 2 5 4 3 1 3 2 2 1 5 2 3 3 1 1 2
 [371] 4 5 3 4 5 5 2 1 3 2 5 4 4 5 3 3 2 4 3 3 2 1 1 5 2 2 1 5 2 2 5 4 4 3 5 4 2
 [408] 5 2 1 3 2 2 3 1 3 1 3 2 1 2 5 1 4 4 4 1 2 1 1 5 4 4 1 3 3 1 3 3 2 3 2 2 2
 [445] 4 2 4 4 1 3 1 2 4 5 4 5 5 2 3 3 4 3 4 1 2 2 1 2 5 4 5 5 5 4 4 4 1 4 5 3 1
 [482] 2 1 1 1 4 3 4 1 4 5 3 5 5 1 4 5 5 5 3 5 5 5 2 2 1 3 3 1 4 4 1 3 5 2 5 5 3
 [519] 2 2 4 3 2 4 2 1 2 2 1 2 1 3 1 1 5 1 5 2 1 4 5 1 5 3 1 3 2 5 2 4 1 4 4 1 1
 [556] 5 3 4 5 3 2 1 3 4 1 3 4 1 5 3 4 1 3 1 3 1 3 1 4 4 4 1 5 4 5 1 4 2 2 5 5 3
 [593] 1 2 3 5 5 4 3 3 2 3 2 1 1 4 2 1 2 5 5 2 5 3 5 3 3 5 1 1 5 3 4 4 2 4 5 5 4
 [630] 3 3 2 3 4 5 1 2 3 5 1 2 1 2 2 4 4 1 5 3 2 5 2 5 3 5 5 1 4 5 1 5 3 1 2 5 1
 [667] 5 5 5 4 4 3 1 1 2 3 2 2 5 5 4 5 1 2 1 4 4 1 1 1 4 4 2 2 2 1 3 5 2 2 2 4 3
 [704] 3 1 3 1 5 3 3 5 4 5 1 1 1 4 4 3 4 5 3 5 3 2 3 2 3 1 4 2 2 3 5 4 5 2 5 5 1
 [741] 4 3 4 3 1 3 1 4 4 5 5 1 4 3 1 4 2 1 2 4 3 5 2 5 5 5 3 5 2 3 4 1 4 1 5 1 3
 [778] 2 5 1 3 4 4 2 5 1 3 4 3 2 3 5 4 2 5 3 3 5 3 1 2 1 3 1 1 1 1 5 1 3 1 5 2 1
 [815] 1 2 2 2 3 2 2 3 2 5 4 4 4 1 3 4 1 3 1 2 4 2 1 5 3 2 3 2 5 4 2 2 4 1 3 4 1
 [852] 2 5 3 3 5 1 5 2 2 5 3 2 1 1 3 1 3 1 1 4 3 2 4 5 5 4 1 5 5 3 2 4 4 5 5 1 4
 [889] 5 1 3 5 1 2 2 2 1 1 3 1 5 3 1 2 4 5 5 1 1 1 2 1 1 5 3 5 3 4 4 5 4 3 5 1 3
 [926] 2 1 3 5 3 1 4 1 4 5 4 3 1 3 4 3 3 5 5 3 3 2 4 5 5 1 4 5 5 4 4 3 1 3 4 1 3
 [963] 1 3 1 4 1 1 1 5 5 2 4 3 3 2 1 1 1 4 5 4 2 1 4 1 1 5 2 3 3 1 3 4 3 2 1 1 5
[1000] 1

Si on utilise la fonction `table` afin de compter l'occurrence de chaque élément

In [7]:
tableau <- table(s)
tableau

s
  1   2   3   4   5 
222 187 203 183 205 

on remarque que chaque élément à été tiré à un taux d'environ 20%

In [18]:
tableau[[1]]/sum(tableau)

[1] 0.222

Si on change les probabilités maintenant, mais **attention** la somme des probabilités doit être égale à 1

In [188]:
s<-sample(1:5, 1000, replace=T, prob=c(.2,.5,.1,.1,.1))
table(s)

s
  1   2   3   4   5 
197 509 101  87 106 

## rnorm
La moyenne par défaut est égale à 0 et l'écart-type=1

In [190]:
rnorm(1)

[1] 0.1068213

In [191]:
rnorm(1, 0, 100)

[1] -24.91306

Créons un vecteur de 100 valeurs avec moyenne=100 et écart-type=100

In [192]:
x<-rnorm(100, 0, 100)

Si on calcule la moyenne de ce vecteur;

In [193]:
mean(x)

[1] -5.832078

Nous avons obtenu une moyenne proche de la moyenne de nos variables aléatoires générées par la fonction `rnorm`

La même chose maintenant pour l'écart-type

In [195]:
sd(x)

[1] 93.11004

Toutefois, si nous augmentons le nombre de variables aléatoires généré, nous sommes alors plus proches des arguments de la fonction `rnorm` que nous avons saisie

In [197]:
x<-rnorm(10000, 0, 100)
mean(x)

[1] 0.9631815

In [198]:
sd(x)

[1] 101.229